"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js/react'

import _recipe_card from './recipe-card.bones.json'

registerBones({
  "recipe-card": _recipe_card,
})
